---
- name: Enable Yum repository
  yum_repository:
    name: influxdb
    description: Influxdb upstream yum repo
    baseurl: "{{ influxdb_repo }}"
    gpgcheck: yes
    gpgkey: "{{ influxdb_repo_key }}"

- name: Import RPM key
  rpm_key:
    key: "{{ influxdb_repo_key }}"
    state: present

# The influxdb package uses `which systemctl` to decide if systemd is
# installed on the target machine. That test fails in the upstream centos
# Docker image because while systemctl(1) is installed, which(1) is not!
# Hence, we install which(1) so that check will pick the right init method.
- name: Install which package
  package:
    name: which-2.20-7.el7
    state: present
  notify:
    - restart influxdb

- name: Install influxdb package
  package:
    name: "influxdb-{{ influxdb_package_version }}"
    state: present
  notify:
    - restart influxdb
